### ISSUE TITLE
OnCreate failed

### ISSUE THREAD

**Issue by oadoad** [volojs/create-responsive-template#18]
Here is the output
volo create catepilla volojs/create-responsive-template
Downloading: https://codeload.github.com/volojs/create-responsive-template/legacy.zip/master
TypeError: Cannot read property 'replace' of null
onCreate did not succeed. You can try later by typing "volo onCreate" inside the project that was just created, passing any arguments you passed to the create call.
https://api.github.com/repos/volojs/create-responsive-template/zipball/master used to create catepilla

I'm on Mac OS X 10.9.5
volo v0.3.6
node 0.12.0
less 1.3.3

**Comment by jrburke** [comment]
This should be fixed now on master, redoing the volo create should complete now. The fixes were just to update dependencies to the latest releases. That said, I have not really tested out this project in a while, so not sure if the newer releases of dependencies mean it will still work.
